# -*- coding: utf-8 -*-
"""Mancala.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1DUb1cdLtUVoMqNi3qrktD_YXdZh5CQHT
"""

!pip install texttable
from texttable import Texttable

def initialize(representation):
  Player1 = [4, 4, 4, 4, 4, 4, 0]
  Player2 = [4, 4, 4, 4, 4, 4, 0]
  representation=[Player1,Player2]
  return representation

def show(representation):
    table = Texttable()
    table.header(["player 2","M2", "P6","P5","P4","P3","P2","P1" ,"M1"])
    table.add_row(["-",representation[1][6],representation[1][5],representation[1][4],representation[1][3],representation[1][2],representation[1][1],representation[1][0], "-"])
    table.add_row(["-","-" ,representation[0][0],representation[0][1],representation[0][2],representation[0][3],representation[0][4],representation[0][5],representation[0][6]])
    table.add_row(["player 1","M2", "P1","P2","P3","P4","P5","P6" ,"M1"])

    print(table.draw())

show(representation)

def takePlayerMove(player,stealing):
    while(1):
        print('player {} move'.format(player+1))
        p= int(input('\n which pocket do you want to move? '))

        if p>6 or p<1 :
            print('Enter a valid pocket number')
            continue

        elif representation[player][p-1] == 0:
            print('Enter a pocket that contains stones')
            continue

        else:
            side=player
            stones=representation[player][p-1]
            representation[player][p-1] = 0

        i=0
        position=p
        for i in range(stones):
            if position==6 and side!=player:
                side=player
                position=0

            if position==6 and side==player:
                representation[side][position]+=1
                if side==0:
                    side=1
                else:
                    side=0


            elif position<6 and position>=0:
                representation[side][position]+=1
            position=(position+1)%7
        if stealing==1:

            if  representation[player][position-1]==1 and side==player:
                if side==0:
                    s=1
                else:
                    s=0
                temp=(6-position)
                representation[player][6]=1+representation[s][temp]+representation[player][6]
                representation[side][position-1]=0
                representation[s][temp]=0
        show(representation)
        if position==0 and side!=player:
            print("you will play again")
        else:
            break

representation=initialize(representation)
#print(representation)
stealing=1 
player=0
show(representation)
while(1):
  takePlayerMove(player,stealing)
  player=1-player

